In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
# Regular EDA(exploratory data analysis) and plotting libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
%matplotlib inline

from tqdm import tqdm
import string
import statistics
import re
import joblib
import random
import statistics
from collections import Counter
from scipy import stats
import os
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D
from sklearn.metrics.pairwise import cosine_similarity
import zipfile
from matplotlib.lines import Line2D

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [3]:
import torch
print(torch.__version__)

2.0.0


In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
type(scalar)

torch.Tensor

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
# vector
vector = torch.tensor([2,4])
vector

tensor([2, 4])

In [9]:
vector.shape, vector.ndim

(torch.Size([2]), 1)

In [10]:
# Matrix
matrix = torch.tensor([[1,2,3],
                      [2,3,4]])
matrix

tensor([[1, 2, 3],
        [2, 3, 4]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 3])

In [13]:
# Tensors
tensor  = torch.tensor([[[1,2, 3],
                         [2, 3, 4],
                         [4,5, 6]], [[2,3,3],
                                     [3,4,3],
                                    [4,5,4]]])
tensor

tensor([[[1, 2, 3],
         [2, 3, 4],
         [4, 5, 6]],

        [[2, 3, 3],
         [3, 4, 3],
         [4, 5, 4]]])

In [14]:
tensor.ndim, tensor.shape

(3, torch.Size([2, 3, 3]))

In [15]:
tensor[1]

tensor([[2, 3, 3],
        [3, 4, 3],
        [4, 5, 4]])

In [16]:
# Create a random tensor of size (3, 4)
random_tensor = torch.randint(low=1, high=11, size=(4, 4), dtype=torch.int32)
random_tensor

tensor([[ 2,  6,  6,  9],
        [ 5,  2,  3,  2],
        [ 9,  9,  2, 10],
        [ 8,  9,  2,  7]], dtype=torch.int32)

In [17]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
random_image_size_tensor[0].shape

torch.Size([224, 3])

In [19]:
zeros = torch.zeros(size=(2,3))
zeros.shape

torch.Size([2, 3])

In [20]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [21]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=-1, end=10, step=1)
zero_to_ten

tensor([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [22]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros, ten_zeros.device

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), device(type='cpu'))

In [23]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [24]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype, float_16_tensor.device

(torch.float16, device(type='cpu'))

In [25]:
# Create a tensor
some_tensor = torch.rand(2, 3)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.6220, 0.9326, 0.6609],
        [0.8620, 0.3646, 0.4095]])
Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [26]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

In [27]:
tensor1 + tensor2

tensor([5, 7, 9])

In [28]:
torch.multiply(tensor1, tensor2)

tensor([ 4, 10, 18])

In [29]:
tensor1*tensor1

tensor([1, 4, 9])

In [30]:
tensor1.shape

torch.Size([3])

In [31]:
torch.matmul(tensor1, tensor2.T)

/tmp/ipykernel_33/1919543094.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /usr/local/src/pytorch/aten/src/ATen/native/TensorShape.cpp:3571.)
  torch.matmul(tensor1, tensor2.T)


tensor(32)

In [32]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [33]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [34]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [35]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Mean: 45.0
Sum: 450


In [36]:
torch.argmax(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(9), tensor(0), tensor(45.), tensor(450))

In [37]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [38]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [39]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [40]:
x_rs = x.reshape(1, 7)
x_rs

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [41]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [42]:
z[:, 0] = 71
z

tensor([[71.,  2.,  3.,  4.,  5.,  6.,  7.]])

In [43]:
x_stk = torch.stack([x,x,x], dim=0)
x_stk

tensor([[71.,  2.,  3.,  4.,  5.,  6.,  7.],
        [71.,  2.,  3.,  4.,  5.,  6.,  7.],
        [71.,  2.,  3.,  4.,  5.,  6.,  7.]])

In [44]:
print(f"Previous tensor: {x_rs}")
print(f"Previous shape: {x_rs.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_rs.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[71.,  2.,  3.,  4.,  5.,  6.,  7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([71.,  2.,  3.,  4.,  5.,  6.,  7.])
New shape: torch.Size([7])


In [45]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([71.,  2.,  3.,  4.,  5.,  6.,  7.])
Previous shape: torch.Size([7])

New tensor: tensor([[71.,  2.,  3.,  4.,  5.,  6.,  7.]])
New shape: torch.Size([1, 7])


In [46]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [60]:
# create a tensor
x = torch.arange(10, 100, 5).reshape(2, 3, 3)
x

tensor([[[10, 15, 20],
         [25, 30, 35],
         [40, 45, 50]],

        [[55, 60, 65],
         [70, 75, 80],
         [85, 90, 95]]])

In [63]:
x[0, 1, 2]

tensor(35)

In [49]:
x, x.ndim

(tensor([[[10, 20, 30],
          [40, 50, 60],
          [70, 80, 90]]]),
 3)

In [72]:
x[0:, 1, :]

tensor([[25, 30, 35],
        [70, 75, 80]])

In [59]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, :, 0]

tensor([[10, 40, 70]])

In [51]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[20, 50, 80]])

In [52]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([50])

In [53]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([10, 20, 30])

In [54]:
arr = np.arange(1.0, 8.0)
tensor = torch.from_numpy(arr).type(torch.float32)
arr, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [55]:
arr+1, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [56]:
tensor = torch.ones(7)
arr = tensor.numpy()
arr, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

In [57]:
tensor = tensor + 1
tensor, arr

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [86]:
torch.manual_seed(42)
# np.random.seed(42)
# Create two random tensors
random_tensor_A = torch.rand(3, 4)

torch.manual_seed(42)
# np.random.seed(42)
random_tensor_B = torch.rand(3, 4)


print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor B:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [87]:
!nvidia-smi

Wed Oct 25 16:35:53 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            Off  | 00000000:00:05.0 Off |                    0 |
| N/A   

In [88]:
torch.cuda.is_available()

True

In [89]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [90]:
torch.cuda.device_count()

2

In [91]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [92]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [96]:
tensor_gpu = tensor.to(device)
tensor, tensor_gpu.device

(tensor([1, 2, 3]), device(type='cuda', index=0))

In [98]:
tensor_gpu.cpu().numpy()

array([1, 2, 3])

In [99]:
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

In [102]:
xarr = torch.arange(1, 11, 1)
xgpu = xarr.to(device)

In [105]:
xnp = xgpu.cpu().numpy()
xnp, xgpu

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], device='cuda:0'))

In [107]:
xgpu[3]

tensor(4, device='cuda:0')